// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#ifndef _SQUARELINE_PROJECT_ESPRESSOMONITOR_UI_H
#define _SQUARELINE_PROJECT_ESPRESSOMONITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_ScreenWarmup.h"
#include "ui_ScreenReady.h"
#include "ui_ScreenBrew.h"
#include "ui_ScreenDone.h"
#include "ui_ScreenSettings.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_487075786);    // assets/blue-water-WHITE_480FX.png
LV_IMG_DECLARE(ui_img_fieldwarcartoon480240blur_reduced_png);    // assets/fieldwarcartoon480240blur_reduced.png
LV_IMG_DECLARE(ui_img_coffeebean20_png);    // assets/coffeebean20.png
LV_IMG_DECLARE(ui_img_character_img5057_png);    // assets/character_img5057.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
