// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#ifndef UI_SCREENWARMUP_H
#define UI_SCREENWARMUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenWarmup
extern void ui_ScreenWarmup_screen_init(void);
extern void ui_ScreenWarmup_screen_destroy(void);
extern lv_obj_t * ui_ScreenWarmup;
extern lv_obj_t * ui_WarmupBarWater;
extern lv_obj_t * ui_WarmupImgWave;
extern lv_obj_t * ui_WarmupPanelOverlay;
extern lv_obj_t * ui_WarmupPanelBottomBar;
extern lv_obj_t * ui_WarmupPanelIcons;
extern lv_obj_t * ui_WarmupLabelWiFi;
extern lv_obj_t * ui_WarmupLabelSD;
extern lv_obj_t * ui_WarmupBtnSettings;
extern lv_obj_t * ui_WarmupLabelSettings;
extern lv_obj_t * ui_WarmupPanelTopBar;
extern lv_obj_t * ui_WarmupLabelStatus;
extern lv_obj_t * ui_WarmupBtnGame;
extern lv_obj_t * ui_WarmupLabelGame;
extern lv_obj_t * ui_WarmupArcBoiler;
extern lv_obj_t * ui_WarmupPanelTemp;
extern lv_obj_t * ui_WarmupLabelBoiler;
extern lv_obj_t * ui_WarmupLabelBoilerTemp;
extern lv_obj_t * ui_WarmupPanelGrouphead;
extern lv_obj_t * ui_WarmupLabelGrouphead;
extern lv_obj_t * ui_WarmupLabelGroupheadTemp;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

