// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#ifndef UI_SCREENWARMUP_H
#define UI_SCREENWARMUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenWarmup
extern void ui_ScreenWarmup_screen_init(void);
extern void ui_ScreenWarmup_screen_destroy(void);
extern lv_obj_t * ui_ScreenWarmup;
extern lv_obj_t * ui_PanelWater;
extern lv_obj_t * ui_ImgWave;
extern lv_obj_t * ui_PanelOverlay;
extern lv_obj_t * ui_PanelBottomBar;
extern lv_obj_t * ui_PanelIcons;
extern lv_obj_t * ui_LabelWiFi;
extern lv_obj_t * ui_LabelSD;
extern lv_obj_t * ui_BtnSettings;
extern lv_obj_t * ui_LabelSettings;
extern lv_obj_t * ui_PanelTopBar;
extern lv_obj_t * ui_LabelStatus;
extern lv_obj_t * ui_BtnGame;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_LabelTemp;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

