// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#ifndef UI_SCREENREADY_H
#define UI_SCREENREADY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenReady
extern void ui_ScreenReady_screen_init(void);
extern void ui_ScreenReady_screen_destroy(void);
extern lv_obj_t * ui_ScreenReady;
extern lv_obj_t * ui_ReadyImageBg;
extern lv_obj_t * ui_ReadyPanelOverlay;
extern lv_obj_t * ui_ReadyPanelBottomBar;
extern lv_obj_t * ui_ReadyPanelIcons;
extern lv_obj_t * ui_ReadyLabelWiFi;
extern lv_obj_t * ui_ReadyLabelSD;
extern lv_obj_t * ui_ReadyBtnSettings;
extern lv_obj_t * ui_ReadyLabelSettings;
extern lv_obj_t * ui_ReadyPanelTopBar;
extern lv_obj_t * ui_ReadyLabelStatus;
extern lv_obj_t * ui_ReadyLabelFlush;
extern lv_obj_t * ui_ReadyPanelTime;
extern lv_obj_t * ui_ReadyLabelTimeSeconds;
extern lv_obj_t * ui_ReadyLabelTimeMinutes;
extern lv_obj_t * ui_ReadyLabelTimeColon;
extern lv_obj_t * ui_ReadyButtonTemp;
extern lv_obj_t * ui_ReadyLabelTemp;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenReady;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

