// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#include "ui.h"

lv_obj_t * ui_ScreenBrew = NULL;
lv_obj_t * ui_BrewPanelOverlay = NULL;
lv_obj_t * ui_BrewPanelBottomBar = NULL;
lv_obj_t * ui_BrewPanelIcons = NULL;
lv_obj_t * ui_BrewLabelWiFi = NULL;
lv_obj_t * ui_BrewLabelSD = NULL;
lv_obj_t * ui_BrewBtnSettings = NULL;
lv_obj_t * ui_BrewLabelSettings = NULL;
lv_obj_t * ui_BrewPanelTopBar = NULL;
lv_obj_t * ui_BrewLabelStatus = NULL;
lv_obj_t * ui_BrewLabelTime = NULL;
lv_obj_t * ui_BrewImageBean = NULL;
lv_obj_t * ui_BrewPanelTime = NULL;
lv_obj_t * ui_BrewLabelTimeTenths = NULL;
lv_obj_t * ui_BrewLabelTimeSeconds = NULL;
lv_obj_t * ui_BrewLabelTimeDot = NULL;
lv_obj_t * ui_BrewLabelTemp = NULL;
lv_obj_t * ui_BrewChart = NULL;
lv_obj_t * ui_BrewChart_Xaxis = NULL;
lv_obj_t * ui_BrewChart_Yaxis1 = NULL;
lv_obj_t * ui_BrewChart_Yaxis2 = NULL;
// event funtions

// build funtions

void ui_ScreenBrew_screen_init(void)
{
    ui_ScreenBrew = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenBrew, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags

    ui_BrewPanelOverlay = lv_obj_create(ui_ScreenBrew);
    lv_obj_set_width(ui_BrewPanelOverlay, 320);
    lv_obj_set_height(ui_BrewPanelOverlay, 240);
    lv_obj_set_align(ui_BrewPanelOverlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewPanelOverlay, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_BrewPanelOverlay,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_BrewPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrewPanelOverlay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_BrewPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BrewPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BrewPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BrewPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BrewPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BrewPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_BrewPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_BrewPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BrewPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BrewPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BrewPanelOverlay, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_BrewPanelBottomBar = lv_obj_create(ui_BrewPanelOverlay);
    lv_obj_set_width(ui_BrewPanelBottomBar, 320);
    lv_obj_set_height(ui_BrewPanelBottomBar, 22);
    lv_obj_set_x(ui_BrewPanelBottomBar, 0);
    lv_obj_set_y(ui_BrewPanelBottomBar, 13);
    lv_obj_set_align(ui_BrewPanelBottomBar, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_BrewPanelBottomBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BrewPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrewPanelBottomBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BrewPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BrewPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BrewPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BrewPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BrewPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_BrewPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_BrewPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewPanelIcons = lv_obj_create(ui_BrewPanelBottomBar);
    lv_obj_set_width(ui_BrewPanelIcons, 60);
    lv_obj_set_height(ui_BrewPanelIcons, 20);
    lv_obj_set_x(ui_BrewPanelIcons, 12);
    lv_obj_set_y(ui_BrewPanelIcons, 0);
    lv_obj_set_align(ui_BrewPanelIcons, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_BrewPanelIcons,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_BrewPanelIcons, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrewPanelIcons, lv_color_hex(0x272727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewPanelIcons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BrewPanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BrewPanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BrewPanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewLabelWiFi = lv_label_create(ui_BrewPanelIcons);
    lv_obj_set_width(ui_BrewLabelWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrewLabelWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrewLabelWiFi, 2);
    lv_obj_set_y(ui_BrewLabelWiFi, 0);
    lv_obj_set_align(ui_BrewLabelWiFi, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BrewLabelWiFi, "");

    ui_BrewLabelSD = lv_label_create(ui_BrewPanelIcons);
    lv_obj_set_width(ui_BrewLabelSD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrewLabelSD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrewLabelSD, -2);
    lv_obj_set_y(ui_BrewLabelSD, 0);
    lv_obj_set_align(ui_BrewLabelSD, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BrewLabelSD, "SD");

    ui_BrewBtnSettings = lv_button_create(ui_BrewPanelBottomBar);
    lv_obj_set_width(ui_BrewBtnSettings, 20);
    lv_obj_set_height(ui_BrewBtnSettings, 20);
    lv_obj_set_x(ui_BrewBtnSettings, -11);
    lv_obj_set_y(ui_BrewBtnSettings, 0);
    lv_obj_set_align(ui_BrewBtnSettings, LV_ALIGN_LEFT_MID);
    lv_obj_set_ext_click_area(ui_BrewBtnSettings, 4);
    lv_obj_add_flag(ui_BrewBtnSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BrewBtnSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BrewBtnSettings, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrewBtnSettings, lv_color_hex(0x7F7F7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewBtnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewLabelSettings = lv_label_create(ui_BrewBtnSettings);
    lv_obj_set_width(ui_BrewLabelSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrewLabelSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrewLabelSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewLabelSettings, "");

    ui_BrewPanelTopBar = lv_obj_create(ui_BrewPanelOverlay);
    lv_obj_set_width(ui_BrewPanelTopBar, lv_pct(100));
    lv_obj_set_height(ui_BrewPanelTopBar, lv_pct(15));
    lv_obj_set_x(ui_BrewPanelTopBar, 0);
    lv_obj_set_y(ui_BrewPanelTopBar, -10);
    lv_obj_set_align(ui_BrewPanelTopBar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_BrewPanelTopBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BrewPanelTopBar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrewPanelTopBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewPanelTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BrewPanelTopBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BrewPanelTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewLabelStatus = lv_label_create(ui_BrewPanelTopBar);
    lv_obj_set_width(ui_BrewLabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrewLabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrewLabelStatus, -10);
    lv_obj_set_y(ui_BrewLabelStatus, 0);
    lv_obj_set_align(ui_BrewLabelStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BrewLabelStatus, "BREWING");
    lv_obj_set_style_text_color(ui_BrewLabelStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrewLabelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_BrewLabelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_BrewLabelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BrewLabelStatus, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_BrewLabelStatus, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewLabelStatus, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewLabelTime = lv_label_create(ui_BrewPanelTopBar);
    lv_obj_set_width(ui_BrewLabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrewLabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrewLabelTime, 12);
    lv_obj_set_y(ui_BrewLabelTime, 0);
    lv_obj_set_align(ui_BrewLabelTime, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BrewLabelTime, "BREW TIME");
    lv_obj_set_style_text_color(ui_BrewLabelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrewLabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_BrewLabelTime, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_BrewLabelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BrewLabelTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewLabelTime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewImageBean = lv_image_create(ui_BrewPanelTopBar);
    lv_image_set_src(ui_BrewImageBean, &ui_img_coffeebean20_png);
    lv_obj_set_width(ui_BrewImageBean, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrewImageBean, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrewImageBean, -50);
    lv_obj_set_y(ui_BrewImageBean, 0);
    lv_obj_set_align(ui_BrewImageBean, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewImageBean, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BrewImageBean, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrewPanelTime = lv_obj_create(ui_BrewPanelOverlay);
    lv_obj_set_width(ui_BrewPanelTime, 150);
    lv_obj_set_height(ui_BrewPanelTime, 60);
    lv_obj_set_x(ui_BrewPanelTime, 108);
    lv_obj_set_y(ui_BrewPanelTime, -60);
    lv_obj_set_align(ui_BrewPanelTime, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BrewPanelTime,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_BrewPanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrewPanelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewPanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BrewPanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BrewPanelTime, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrewPanelTime, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewPanelTime, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_BrewLabelTimeTenths = lv_label_create(ui_BrewPanelTime);
    lv_obj_set_width(ui_BrewLabelTimeTenths, 45);
    lv_obj_set_height(ui_BrewLabelTimeTenths, 60);
    lv_obj_set_x(ui_BrewLabelTimeTenths, 25);
    lv_obj_set_y(ui_BrewLabelTimeTenths, 0);
    lv_obj_set_align(ui_BrewLabelTimeTenths, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewLabelTimeTenths, "8");
    lv_obj_remove_flag(ui_BrewLabelTimeTenths,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_BrewLabelTimeTenths, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrewLabelTimeTenths, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BrewLabelTimeTenths, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewLabelTimeTenths, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewLabelTimeSeconds = lv_label_create(ui_BrewPanelTime);
    lv_obj_set_width(ui_BrewLabelTimeSeconds, 75);
    lv_obj_set_height(ui_BrewLabelTimeSeconds, 60);
    lv_obj_set_x(ui_BrewLabelTimeSeconds, -40);
    lv_obj_set_y(ui_BrewLabelTimeSeconds, 0);
    lv_obj_set_align(ui_BrewLabelTimeSeconds, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewLabelTimeSeconds, "88");
    lv_obj_remove_flag(ui_BrewLabelTimeSeconds,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_BrewLabelTimeSeconds, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrewLabelTimeSeconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BrewLabelTimeSeconds, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewLabelTimeSeconds, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewLabelTimeDot = lv_label_create(ui_BrewPanelTime);
    lv_obj_set_width(ui_BrewLabelTimeDot, 20);
    lv_obj_set_height(ui_BrewLabelTimeDot, 60);
    lv_obj_set_align(ui_BrewLabelTimeDot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewLabelTimeDot, ".");
    lv_obj_remove_flag(ui_BrewLabelTimeDot,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_BrewLabelTimeDot, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewLabelTimeDot, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewLabelTemp = lv_label_create(ui_BrewPanelOverlay);
    lv_obj_set_width(ui_BrewLabelTemp, 175);
    lv_obj_set_height(ui_BrewLabelTemp, 60);
    lv_obj_set_x(ui_BrewLabelTemp, -75);
    lv_obj_set_y(ui_BrewLabelTemp, -60);
    lv_obj_set_align(ui_BrewLabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewLabelTemp, "100.8C");
    lv_obj_remove_flag(ui_BrewLabelTemp,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_BrewLabelTemp, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrewLabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BrewLabelTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewLabelTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewChart = lv_chart_create(ui_BrewPanelOverlay);
    lv_obj_set_width(ui_BrewChart, 280);
    lv_obj_set_height(ui_BrewChart, 120);
    lv_obj_set_x(ui_BrewChart, 15);
    lv_obj_set_y(ui_BrewChart, -10);
    lv_obj_set_align(ui_BrewChart, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BrewChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_BrewChart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_BrewChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_BrewChart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_BrewChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_BrewChart, 100);
    lv_chart_set_axis_range(ui_BrewChart, LV_CHART_AXIS_PRIMARY_Y, 90, 120);
    lv_chart_set_div_line_count(ui_BrewChart, 8, 30);
    lv_obj_set_style_radius(ui_BrewChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrewChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BrewChart, lv_color_hex(0x4F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BrewChart, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BrewChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BrewChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_BrewChart, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_BrewChart, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewChart_Xaxis = lv_scale_create(ui_BrewChart);
    lv_scale_set_mode(ui_BrewChart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_BrewChart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_BrewChart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_BrewChart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_BrewChart,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_BrewChart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_BrewChart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_BrewChart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_BrewChart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_BrewChart_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_BrewChart_Xaxis, 2, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_BrewChart_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_BrewChart_Xaxis, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_BrewChart_Xaxis, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_BrewChart_Xaxis, false);
    ui_BrewChart_Yaxis1 = lv_scale_create(ui_BrewChart);
    lv_scale_set_mode(ui_BrewChart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_BrewChart_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_BrewChart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_BrewChart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_BrewChart,
                                                                      LV_PART_MAIN) - lv_obj_get_style_border_width(ui_BrewChart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_BrewChart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_BrewChart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_BrewChart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_BrewChart_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_BrewChart_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_BrewChart_Yaxis1,  90, 120);
    lv_scale_set_total_tick_count(ui_BrewChart_Yaxis1, (8 > 0 ? 8 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_BrewChart_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_BrewChart_Yaxis2 = lv_scale_create(ui_BrewChart);
    lv_scale_set_mode(ui_BrewChart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_BrewChart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_BrewChart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_BrewChart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_BrewChart,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_BrewChart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_BrewChart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_BrewChart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_BrewChart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_BrewChart_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_BrewChart_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_BrewChart_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_BrewChart_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_BrewChart_Yaxis2, false);

    lv_obj_set_style_line_color(ui_BrewChart, lv_color_hex(0xFF0000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_BrewChart, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_BrewChart, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BrewChart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrewChart, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewChart, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BrewChart, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BrewChart, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BrewChart, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_BrewChart, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_BrewChart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenBrew_screen_destroy(void)
{
    if(ui_ScreenBrew) lv_obj_del(ui_ScreenBrew);

    // NULL screen variables
    ui_ScreenBrew = NULL;
    ui_BrewPanelOverlay = NULL;
    ui_BrewPanelBottomBar = NULL;
    ui_BrewPanelIcons = NULL;
    ui_BrewLabelWiFi = NULL;
    ui_BrewLabelSD = NULL;
    ui_BrewBtnSettings = NULL;
    ui_BrewLabelSettings = NULL;
    ui_BrewPanelTopBar = NULL;
    ui_BrewLabelStatus = NULL;
    ui_BrewLabelTime = NULL;
    ui_BrewImageBean = NULL;
    ui_BrewPanelTime = NULL;
    ui_BrewLabelTimeTenths = NULL;
    ui_BrewLabelTimeSeconds = NULL;
    ui_BrewLabelTimeDot = NULL;
    ui_BrewLabelTemp = NULL;
    ui_BrewChart = NULL;

}
