// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#ifndef UI_SCREENBREW_H
#define UI_SCREENBREW_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenBrew
extern void ui_ScreenBrew_screen_init(void);
extern void ui_ScreenBrew_screen_destroy(void);
extern lv_obj_t * ui_ScreenBrew;
extern lv_obj_t * ui_BrewPanelOverlay;
extern lv_obj_t * ui_BrewPanelBottomBar;
extern lv_obj_t * ui_BrewPanelIcons;
extern lv_obj_t * ui_BrewLabelWiFi;
extern lv_obj_t * ui_BrewLabelSD;
extern lv_obj_t * ui_BrewBtnSettings;
extern lv_obj_t * ui_BrewLabelSettings;
extern lv_obj_t * ui_BrewPanelTopBar;
extern lv_obj_t * ui_BrewLabelStatus;
extern lv_obj_t * ui_BrewLabelTime;
extern lv_obj_t * ui_BrewImageBean;
extern lv_obj_t * ui_BrewPanelTime;
extern lv_obj_t * ui_BrewLabelTimeTenths;
extern lv_obj_t * ui_BrewLabelTimeSeconds;
extern lv_obj_t * ui_BrewLabelTimeDot;
extern lv_obj_t * ui_BrewLabelTemp;
extern lv_obj_t * ui_BrewChart;
extern lv_obj_t * ui_BrewChart_Xaxis;
extern lv_obj_t * ui_BrewChart_Yaxis1;
extern lv_obj_t * ui_BrewChart_Yaxis2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

