// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#include "ui.h"

lv_obj_t * ui_ScreenDone = NULL;
lv_obj_t * ui_DonePanelOverlay = NULL;
lv_obj_t * ui_DonePanelBottomBar = NULL;
lv_obj_t * ui_DonePanelIcons = NULL;
lv_obj_t * ui_DoneLabelWiFi = NULL;
lv_obj_t * ui_DoneLabelSD = NULL;
lv_obj_t * ui_DoneBtnSettings = NULL;
lv_obj_t * ui_DoneLabelSettings = NULL;
lv_obj_t * ui_DonePanelTopBar = NULL;
lv_obj_t * ui_DoneLabelStatus = NULL;
lv_obj_t * ui_DoneLabelUploading = NULL;
lv_obj_t * ui_DoneChart = NULL;
lv_obj_t * ui_DoneChart_Xaxis = NULL;
lv_obj_t * ui_DoneChart_Yaxis1 = NULL;
lv_obj_t * ui_DoneChart_Yaxis2 = NULL;
lv_obj_t * ui_DonePanelTime = NULL;
lv_obj_t * ui_DoneLabelTimeTenths = NULL;
lv_obj_t * ui_DoneLabelTimeSeconds = NULL;
lv_obj_t * ui_DoneLabelTimeDot = NULL;
lv_obj_t * ui_DonePanelRate = NULL;
lv_obj_t * ui_DoneImageGuy = NULL;
lv_obj_t * ui_DoneLabelRate = NULL;
lv_obj_t * ui_DoneSliderRate = NULL;
// event funtions

// build funtions

void ui_ScreenDone_screen_init(void)
{
    ui_ScreenDone = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenDone, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags

    ui_DonePanelOverlay = lv_obj_create(ui_ScreenDone);
    lv_obj_set_width(ui_DonePanelOverlay, 320);
    lv_obj_set_height(ui_DonePanelOverlay, 240);
    lv_obj_set_align(ui_DonePanelOverlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DonePanelOverlay, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_DonePanelOverlay,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_DonePanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DonePanelOverlay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DonePanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_DonePanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DonePanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DonePanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DonePanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_DonePanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_DonePanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_DonePanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_DonePanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_DonePanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_DonePanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_DonePanelOverlay, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_DonePanelBottomBar = lv_obj_create(ui_DonePanelOverlay);
    lv_obj_set_width(ui_DonePanelBottomBar, 320);
    lv_obj_set_height(ui_DonePanelBottomBar, 22);
    lv_obj_set_x(ui_DonePanelBottomBar, 0);
    lv_obj_set_y(ui_DonePanelBottomBar, 13);
    lv_obj_set_align(ui_DonePanelBottomBar, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_DonePanelBottomBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DonePanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DonePanelBottomBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DonePanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DonePanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DonePanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DonePanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_DonePanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_DonePanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_DonePanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_DonePanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DonePanelIcons = lv_obj_create(ui_DonePanelBottomBar);
    lv_obj_set_width(ui_DonePanelIcons, 60);
    lv_obj_set_height(ui_DonePanelIcons, 20);
    lv_obj_set_x(ui_DonePanelIcons, 12);
    lv_obj_set_y(ui_DonePanelIcons, 0);
    lv_obj_set_align(ui_DonePanelIcons, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_DonePanelIcons,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_DonePanelIcons, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DonePanelIcons, lv_color_hex(0x272727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DonePanelIcons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DonePanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DonePanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DonePanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoneLabelWiFi = lv_label_create(ui_DonePanelIcons);
    lv_obj_set_width(ui_DoneLabelWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoneLabelWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DoneLabelWiFi, 2);
    lv_obj_set_y(ui_DoneLabelWiFi, 0);
    lv_obj_set_align(ui_DoneLabelWiFi, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_DoneLabelWiFi, "");

    ui_DoneLabelSD = lv_label_create(ui_DonePanelIcons);
    lv_obj_set_width(ui_DoneLabelSD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoneLabelSD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DoneLabelSD, -2);
    lv_obj_set_y(ui_DoneLabelSD, 0);
    lv_obj_set_align(ui_DoneLabelSD, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DoneLabelSD, "SD");

    ui_DoneBtnSettings = lv_button_create(ui_DonePanelBottomBar);
    lv_obj_set_width(ui_DoneBtnSettings, 20);
    lv_obj_set_height(ui_DoneBtnSettings, 20);
    lv_obj_set_x(ui_DoneBtnSettings, -11);
    lv_obj_set_y(ui_DoneBtnSettings, 0);
    lv_obj_set_align(ui_DoneBtnSettings, LV_ALIGN_LEFT_MID);
    lv_obj_set_ext_click_area(ui_DoneBtnSettings, 4);
    lv_obj_add_flag(ui_DoneBtnSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DoneBtnSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DoneBtnSettings, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DoneBtnSettings, lv_color_hex(0x7F7F7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DoneBtnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoneLabelSettings = lv_label_create(ui_DoneBtnSettings);
    lv_obj_set_width(ui_DoneLabelSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoneLabelSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DoneLabelSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoneLabelSettings, "");

    ui_DonePanelTopBar = lv_obj_create(ui_DonePanelOverlay);
    lv_obj_set_width(ui_DonePanelTopBar, lv_pct(100));
    lv_obj_set_height(ui_DonePanelTopBar, lv_pct(15));
    lv_obj_set_x(ui_DonePanelTopBar, 0);
    lv_obj_set_y(ui_DonePanelTopBar, -10);
    lv_obj_set_align(ui_DonePanelTopBar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_DonePanelTopBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DonePanelTopBar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DonePanelTopBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DonePanelTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DonePanelTopBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DonePanelTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoneLabelStatus = lv_label_create(ui_DonePanelTopBar);
    lv_obj_set_width(ui_DoneLabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoneLabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DoneLabelStatus, -10);
    lv_obj_set_y(ui_DoneLabelStatus, 0);
    lv_obj_set_align(ui_DoneLabelStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DoneLabelStatus, "DONE");
    lv_obj_set_style_text_color(ui_DoneLabelStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DoneLabelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_DoneLabelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_DoneLabelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DoneLabelStatus, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_DoneLabelStatus, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DoneLabelStatus, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoneLabelUploading = lv_label_create(ui_DonePanelTopBar);
    lv_obj_set_width(ui_DoneLabelUploading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoneLabelUploading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DoneLabelUploading, 10);
    lv_obj_set_y(ui_DoneLabelUploading, 0);
    lv_obj_set_align(ui_DoneLabelUploading, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_DoneLabelUploading, "UPLOADING TO SERVER...");
    lv_obj_set_style_text_color(ui_DoneLabelUploading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DoneLabelUploading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DoneLabelUploading, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DoneLabelUploading, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DoneLabelUploading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoneChart = lv_chart_create(ui_DonePanelOverlay);
    lv_obj_set_width(ui_DoneChart, 280);
    lv_obj_set_height(ui_DoneChart, 120);
    lv_obj_set_x(ui_DoneChart, 15);
    lv_obj_set_y(ui_DoneChart, -10);
    lv_obj_set_align(ui_DoneChart, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_DoneChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_DoneChart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_DoneChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_DoneChart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_DoneChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_DoneChart, 100);
    lv_chart_set_axis_range(ui_DoneChart, LV_CHART_AXIS_PRIMARY_Y, 90, 120);
    lv_chart_set_div_line_count(ui_DoneChart, 8, 30);
    lv_obj_set_style_radius(ui_DoneChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DoneChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DoneChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DoneChart, lv_color_hex(0x4F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DoneChart, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DoneChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DoneChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_DoneChart, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_DoneChart, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoneChart_Xaxis = lv_scale_create(ui_DoneChart);
    lv_scale_set_mode(ui_DoneChart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_DoneChart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_DoneChart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_DoneChart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_DoneChart,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_DoneChart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_DoneChart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_DoneChart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_DoneChart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_DoneChart_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_DoneChart_Xaxis, 2, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_DoneChart_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_DoneChart_Xaxis, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_DoneChart_Xaxis, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_DoneChart_Xaxis, false);
    ui_DoneChart_Yaxis1 = lv_scale_create(ui_DoneChart);
    lv_scale_set_mode(ui_DoneChart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_DoneChart_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_DoneChart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_DoneChart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_DoneChart,
                                                                      LV_PART_MAIN) - lv_obj_get_style_border_width(ui_DoneChart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_DoneChart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_DoneChart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_DoneChart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_DoneChart_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_DoneChart_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_DoneChart_Yaxis1,  90, 120);
    lv_scale_set_total_tick_count(ui_DoneChart_Yaxis1, (8 > 0 ? 8 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_DoneChart_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_DoneChart_Yaxis2 = lv_scale_create(ui_DoneChart);
    lv_scale_set_mode(ui_DoneChart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_DoneChart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_DoneChart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_DoneChart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_DoneChart,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_DoneChart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_DoneChart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_DoneChart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_DoneChart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_DoneChart_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_DoneChart_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_DoneChart_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_DoneChart_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_DoneChart_Yaxis2, false);

    lv_obj_set_style_line_color(ui_DoneChart, lv_color_hex(0xFF0000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_DoneChart, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_DoneChart, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_DoneChart, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DoneChart, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DoneChart, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DoneChart, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DoneChart, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DoneChart, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_DoneChart, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_DoneChart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_DonePanelTime = lv_obj_create(ui_DonePanelOverlay);
    lv_obj_set_width(ui_DonePanelTime, 150);
    lv_obj_set_height(ui_DonePanelTime, 60);
    lv_obj_set_x(ui_DonePanelTime, 5);
    lv_obj_set_y(ui_DonePanelTime, 30);
    lv_obj_set_align(ui_DonePanelTime, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DonePanelTime,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_DonePanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DonePanelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DonePanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DonePanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_DonePanelTime, 300, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_DonePanelTime, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DonePanelTime, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DonePanelTime, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_DoneLabelTimeTenths = lv_label_create(ui_DonePanelTime);
    lv_obj_set_width(ui_DoneLabelTimeTenths, 45);
    lv_obj_set_height(ui_DoneLabelTimeTenths, 60);
    lv_obj_set_x(ui_DoneLabelTimeTenths, 25);
    lv_obj_set_y(ui_DoneLabelTimeTenths, 0);
    lv_obj_set_align(ui_DoneLabelTimeTenths, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoneLabelTimeTenths, "8");
    lv_obj_remove_flag(ui_DoneLabelTimeTenths,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_DoneLabelTimeTenths, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DoneLabelTimeTenths, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DoneLabelTimeTenths, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DoneLabelTimeTenths, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoneLabelTimeSeconds = lv_label_create(ui_DonePanelTime);
    lv_obj_set_width(ui_DoneLabelTimeSeconds, 75);
    lv_obj_set_height(ui_DoneLabelTimeSeconds, 60);
    lv_obj_set_x(ui_DoneLabelTimeSeconds, -40);
    lv_obj_set_y(ui_DoneLabelTimeSeconds, 0);
    lv_obj_set_align(ui_DoneLabelTimeSeconds, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoneLabelTimeSeconds, "88");
    lv_obj_remove_flag(ui_DoneLabelTimeSeconds,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_DoneLabelTimeSeconds, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DoneLabelTimeSeconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DoneLabelTimeSeconds, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DoneLabelTimeSeconds, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoneLabelTimeDot = lv_label_create(ui_DonePanelTime);
    lv_obj_set_width(ui_DoneLabelTimeDot, 20);
    lv_obj_set_height(ui_DoneLabelTimeDot, 60);
    lv_obj_set_align(ui_DoneLabelTimeDot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoneLabelTimeDot, ".");
    lv_obj_remove_flag(ui_DoneLabelTimeDot,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_DoneLabelTimeDot, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DoneLabelTimeDot, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DonePanelRate = lv_obj_create(ui_DonePanelOverlay);
    lv_obj_set_width(ui_DonePanelRate, 320);
    lv_obj_set_height(ui_DonePanelRate, 50);
    lv_obj_set_x(ui_DonePanelRate, 0);
    lv_obj_set_y(ui_DonePanelRate, -60);
    lv_obj_set_align(ui_DonePanelRate, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DonePanelRate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DonePanelRate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DonePanelRate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DonePanelRate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DonePanelRate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DonePanelRate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DonePanelRate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoneImageGuy = lv_image_create(ui_DonePanelRate);
    lv_image_set_src(ui_DoneImageGuy, &ui_img_character_img5057_png);
    lv_obj_set_width(ui_DoneImageGuy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoneImageGuy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DoneImageGuy, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DoneImageGuy, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DoneImageGuy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_DoneImageGuy, 220);

    ui_DoneLabelRate = lv_label_create(ui_DonePanelRate);
    lv_obj_set_width(ui_DoneLabelRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoneLabelRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DoneLabelRate, 45);
    lv_obj_set_y(ui_DoneLabelRate, -10);
    lv_obj_set_align(ui_DoneLabelRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoneLabelRate, "RATE THIS SHOT");
    lv_obj_set_style_text_letter_space(ui_DoneLabelRate, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_DoneLabelRate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DoneLabelRate, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoneSliderRate = lv_slider_create(ui_DonePanelRate);
    lv_slider_set_range(ui_DoneSliderRate, 0, 10);
    lv_slider_set_value(ui_DoneSliderRate, 4, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_DoneSliderRate) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_DoneSliderRate, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_DoneSliderRate, 200);
    lv_obj_set_height(ui_DoneSliderRate, 15);
    lv_obj_set_x(ui_DoneSliderRate, 0);
    lv_obj_set_y(ui_DoneSliderRate, 10);
    lv_obj_set_align(ui_DoneSliderRate, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_DoneSliderRate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DoneSliderRate, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DoneSliderRate, lv_color_hex(0x5B3121), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DoneSliderRate, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DoneSliderRate, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DoneSliderRate, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_DoneSliderRate, &ui_img_coffeebean20_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_DoneSliderRate, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_DoneSliderRate,
                                                                                                     lv_obj_get_style_pad_right(ui_DoneSliderRate, LV_PART_MAIN) + 1, LV_PART_MAIN);

}

void ui_ScreenDone_screen_destroy(void)
{
    if(ui_ScreenDone) lv_obj_del(ui_ScreenDone);

    // NULL screen variables
    ui_ScreenDone = NULL;
    ui_DonePanelOverlay = NULL;
    ui_DonePanelBottomBar = NULL;
    ui_DonePanelIcons = NULL;
    ui_DoneLabelWiFi = NULL;
    ui_DoneLabelSD = NULL;
    ui_DoneBtnSettings = NULL;
    ui_DoneLabelSettings = NULL;
    ui_DonePanelTopBar = NULL;
    ui_DoneLabelStatus = NULL;
    ui_DoneLabelUploading = NULL;
    ui_DoneChart = NULL;
    ui_DonePanelTime = NULL;
    ui_DoneLabelTimeTenths = NULL;
    ui_DoneLabelTimeSeconds = NULL;
    ui_DoneLabelTimeDot = NULL;
    ui_DonePanelRate = NULL;
    ui_DoneImageGuy = NULL;
    ui_DoneLabelRate = NULL;
    ui_DoneSliderRate = NULL;

}
