// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#include "ui.h"

lv_obj_t * ui_ScreenWarmup = NULL;
lv_obj_t * ui_PanelWater = NULL;
lv_obj_t * ui_ImgWave = NULL;
lv_obj_t * ui_PanelOverlay = NULL;
lv_obj_t * ui_PanelBottomBar = NULL;
lv_obj_t * ui_PanelIcons = NULL;
lv_obj_t * ui_LabelWiFi = NULL;
lv_obj_t * ui_LabelSD = NULL;
lv_obj_t * ui_BtnSettings = NULL;
lv_obj_t * ui_LabelSettings = NULL;
lv_obj_t * ui_PanelTopBar = NULL;
lv_obj_t * ui_LabelStatus = NULL;
lv_obj_t * ui_BtnGame = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_LabelTemp = NULL;
// event funtions

// build funtions

void ui_ScreenWarmup_screen_init(void)
{
    ui_ScreenWarmup = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenWarmup, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags

    ui_PanelWater = lv_obj_create(ui_ScreenWarmup);
    lv_obj_set_width(ui_PanelWater, lv_pct(100));
    lv_obj_set_height(ui_PanelWater, lv_pct(100));
    lv_obj_set_align(ui_PanelWater, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_PanelWater, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_PanelWater, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_PanelWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgWave = lv_image_create(ui_ScreenWarmup);
    lv_image_set_src(ui_ImgWave, &ui_img_487075786);
    lv_obj_set_width(ui_ImgWave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgWave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgWave, 0);
    lv_obj_set_y(ui_ImgWave, lv_pct(55));
    lv_obj_set_align(ui_ImgWave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWave, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_ImgWave, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_inner_align(ui_ImgWave, LV_IMAGE_ALIGN_TOP_MID);
    lv_obj_set_style_image_recolor(ui_ImgWave, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_ImgWave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelOverlay = lv_obj_create(ui_ScreenWarmup);
    lv_obj_set_width(ui_PanelOverlay, lv_pct(100));
    lv_obj_set_height(ui_PanelOverlay, lv_pct(100));
    lv_obj_set_align(ui_PanelOverlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelOverlay, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_PanelOverlay, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_PanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelOverlay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_PanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBottomBar = lv_obj_create(ui_PanelOverlay);
    lv_obj_set_width(ui_PanelBottomBar, 320);
    lv_obj_set_height(ui_PanelBottomBar, lv_pct(10));
    lv_obj_set_x(ui_PanelBottomBar, 0);
    lv_obj_set_y(ui_PanelBottomBar, 10);
    lv_obj_set_align(ui_PanelBottomBar, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_PanelBottomBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelIcons = lv_obj_create(ui_PanelBottomBar);
    lv_obj_set_width(ui_PanelIcons, 70);
    lv_obj_set_height(ui_PanelIcons, 20);
    lv_obj_set_x(ui_PanelIcons, 20);
    lv_obj_set_y(ui_PanelIcons, 0);
    lv_obj_set_align(ui_PanelIcons, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_PanelIcons, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_PanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWiFi = lv_label_create(ui_PanelIcons);
    lv_obj_set_width(ui_LabelWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWiFi, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelWiFi, "");

    ui_LabelSD = lv_label_create(ui_PanelIcons);
    lv_obj_set_width(ui_LabelSD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSD, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelSD, "SD");

    ui_BtnSettings = lv_button_create(ui_PanelBottomBar);
    lv_obj_set_width(ui_BtnSettings, 20);
    lv_obj_set_height(ui_BtnSettings, 20);
    lv_obj_set_x(ui_BtnSettings, -10);
    lv_obj_set_y(ui_BtnSettings, 0);
    lv_obj_set_align(ui_BtnSettings, LV_ALIGN_LEFT_MID);
    lv_obj_set_ext_click_area(ui_BtnSettings, 2);
    lv_obj_add_flag(ui_BtnSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnSettings, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSettings, lv_color_hex(0x7F7F7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSettings = lv_label_create(ui_BtnSettings);
    lv_obj_set_width(ui_LabelSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSettings, "");

    ui_PanelTopBar = lv_obj_create(ui_PanelOverlay);
    lv_obj_set_width(ui_PanelTopBar, lv_pct(100));
    lv_obj_set_height(ui_PanelTopBar, lv_pct(15));
    lv_obj_set_align(ui_PanelTopBar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_PanelTopBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTopBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTopBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStatus = lv_label_create(ui_PanelTopBar);
    lv_obj_set_width(ui_LabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelStatus, "WARMUP");
    lv_obj_set_style_text_color(ui_LabelStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelStatus, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LabelStatus, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStatus, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnGame = lv_button_create(ui_PanelTopBar);
    lv_obj_set_width(ui_BtnGame, 100);
    lv_obj_set_height(ui_BtnGame, 50);
    lv_obj_set_align(ui_BtnGame, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnGame, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnGame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_BtnGame);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "GAME");

    ui_LabelTemp = lv_label_create(ui_PanelOverlay);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "25.0C");

}

void ui_ScreenWarmup_screen_destroy(void)
{
    if(ui_ScreenWarmup) lv_obj_del(ui_ScreenWarmup);

    // NULL screen variables
    ui_ScreenWarmup = NULL;
    ui_PanelWater = NULL;
    ui_ImgWave = NULL;
    ui_PanelOverlay = NULL;
    ui_PanelBottomBar = NULL;
    ui_PanelIcons = NULL;
    ui_LabelWiFi = NULL;
    ui_LabelSD = NULL;
    ui_BtnSettings = NULL;
    ui_LabelSettings = NULL;
    ui_PanelTopBar = NULL;
    ui_LabelStatus = NULL;
    ui_BtnGame = NULL;
    ui_Label2 = NULL;
    ui_LabelTemp = NULL;

}
