SET(SOURCES ui_ScreenWarmup.c
    ui_ScreenReady.c
    ui_ScreenBrew.c
    ui_ScreenDone.c
    ui_ScreenSettings.c
    ui.c
    ui_comp_hook.c
    ui_helpers.c
    ui_img_487075786.c
    ui_img_fieldwarcartoon480240blur_reduced_png.c
    ui_img_coffeebean20_png.c
    ui_img_character_img5057_png.c)

add_library(ui ${SOURCES})
