// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#include "ui.h"

lv_obj_t * ui_ScreenSettings = NULL;
lv_obj_t * ui_SettingsPanelMain = NULL;
lv_obj_t * ui_SettingsDropdownGHTemp = NULL;
lv_obj_t * ui_SettingsDropdownBoilerTemp = NULL;
lv_obj_t * ui_SettingsDropdownMusicSelect = NULL;
lv_obj_t * ui_SettingsButtonCalibrateSoakTime = NULL;
lv_obj_t * ui_SettingsSpinboxHeatsoak = NULL;
lv_obj_t * ui_SettingsLabelCalibrateSoakTime = NULL;
lv_obj_t * ui_SettingsButtonClearLogs = NULL;
lv_obj_t * ui_SettingsLabelClearLogs = NULL;
lv_obj_t * ui_SettingsButtonExit = NULL;
lv_obj_t * ui_SettingsLabelExit = NULL;
lv_obj_t * ui_SettingsContainerSD = NULL;
lv_obj_t * ui_SettingsLabelSDTitle = NULL;
lv_obj_t * ui_SettingsLabelSDFree = NULL;
lv_obj_t * ui_SettingsContainerBrewCount = NULL;
lv_obj_t * ui_SettingsLabelBrewCountTitle = NULL;
lv_obj_t * ui_SettingsLabelBrewCountNum = NULL;
lv_obj_t * ui_SettingsContainerFWVer = NULL;
lv_obj_t * ui_SettingsLabelFWVerTitle = NULL;
lv_obj_t * ui_SettingsLabelFWVerNum = NULL;
// event funtions

// build funtions

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsPanelMain = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_SettingsPanelMain, 320);
    lv_obj_set_height(ui_SettingsPanelMain, 240);
    lv_obj_set_align(ui_SettingsPanelMain, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_SettingsPanelMain, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_SettingsPanelMain, LV_DIR_VER);
    lv_obj_set_style_radius(ui_SettingsPanelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_SettingsPanelMain, &ui_img_fieldwarcartoon480240blur_reduced_png,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_SettingsPanelMain, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsPanelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsDropdownGHTemp = lv_dropdown_create(ui_SettingsPanelMain);
    lv_dropdown_set_options(ui_SettingsDropdownGHTemp, "85\n86\n87\n88\n89\n90\n91\n92\n93");
    lv_dropdown_set_text(ui_SettingsDropdownGHTemp, "tgt. GH Temp");
    lv_obj_set_width(ui_SettingsDropdownGHTemp, 240);
    lv_obj_set_height(ui_SettingsDropdownGHTemp, 40);
    lv_obj_set_x(ui_SettingsDropdownGHTemp, -30);
    lv_obj_set_y(ui_SettingsDropdownGHTemp, -90);
    lv_obj_set_align(ui_SettingsDropdownGHTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsDropdownGHTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_SettingsDropdownGHTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsDropdownGHTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsDropdownGHTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsDropdownGHTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsDropdownBoilerTemp = lv_dropdown_create(ui_SettingsPanelMain);
    lv_dropdown_set_options(ui_SettingsDropdownBoilerTemp, "115\n116\n117\n118\n119\n120\n121\n122\n123\n124\n125");
    lv_dropdown_set_text(ui_SettingsDropdownBoilerTemp, "tgt. Boiler Temp");
    lv_obj_set_width(ui_SettingsDropdownBoilerTemp, 240);
    lv_obj_set_height(ui_SettingsDropdownBoilerTemp, 40);
    lv_obj_set_x(ui_SettingsDropdownBoilerTemp, -30);
    lv_obj_set_y(ui_SettingsDropdownBoilerTemp, -40);
    lv_obj_set_align(ui_SettingsDropdownBoilerTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsDropdownBoilerTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_SettingsDropdownBoilerTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsDropdownBoilerTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsDropdownBoilerTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsDropdownBoilerTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsDropdownMusicSelect = lv_dropdown_create(ui_SettingsPanelMain);
    lv_dropdown_set_options(ui_SettingsDropdownMusicSelect, "Helldivers\nDoom\nMUTE");
    lv_dropdown_set_text(ui_SettingsDropdownMusicSelect, "Select Music");
    lv_obj_set_width(ui_SettingsDropdownMusicSelect, 240);
    lv_obj_set_height(ui_SettingsDropdownMusicSelect, 40);
    lv_obj_set_x(ui_SettingsDropdownMusicSelect, -30);
    lv_obj_set_y(ui_SettingsDropdownMusicSelect, 10);
    lv_obj_set_align(ui_SettingsDropdownMusicSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsDropdownMusicSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_SettingsDropdownMusicSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsDropdownMusicSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsDropdownMusicSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsDropdownMusicSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButtonCalibrateSoakTime = lv_button_create(ui_SettingsPanelMain);
    lv_obj_set_width(ui_SettingsButtonCalibrateSoakTime, 240);
    lv_obj_set_height(ui_SettingsButtonCalibrateSoakTime, 60);
    lv_obj_set_x(ui_SettingsButtonCalibrateSoakTime, -30);
    lv_obj_set_y(ui_SettingsButtonCalibrateSoakTime, 70);
    lv_obj_set_align(ui_SettingsButtonCalibrateSoakTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButtonCalibrateSoakTime, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettingsButtonCalibrateSoakTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsButtonCalibrateSoakTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsButtonCalibrateSoakTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsButtonCalibrateSoakTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsButtonCalibrateSoakTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsButtonCalibrateSoakTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsButtonCalibrateSoakTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsSpinboxHeatsoak = lv_spinbox_create(ui_SettingsPanelMain);
    lv_obj_set_width(ui_SettingsSpinboxHeatsoak, 240);
    lv_obj_set_height(ui_SettingsSpinboxHeatsoak, 40);
    lv_obj_set_x(ui_SettingsSpinboxHeatsoak, -30);
    lv_obj_set_y(ui_SettingsSpinboxHeatsoak, 60);
    lv_obj_set_align(ui_SettingsSpinboxHeatsoak, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_SettingsSpinboxHeatsoak, 3, 2);
    lv_spinbox_set_range(ui_SettingsSpinboxHeatsoak, 0, 999);
    lv_spinbox_set_cursor_pos(ui_SettingsSpinboxHeatsoak, 1 - 1);
    lv_obj_set_style_radius(ui_SettingsSpinboxHeatsoak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsSpinboxHeatsoak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsSpinboxHeatsoak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsSpinboxHeatsoak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SettingsSpinboxHeatsoak, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsSpinboxHeatsoak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SettingsSpinboxHeatsoak, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsSpinboxHeatsoak, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(ui_SettingsSpinboxHeatsoak, LV_TEXT_ALIGN_AUTO, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsSpinboxHeatsoak, &lv_font_montserrat_24, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_SettingsLabelCalibrateSoakTime = lv_label_create(ui_SettingsSpinboxHeatsoak);
    lv_obj_set_width(ui_SettingsLabelCalibrateSoakTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelCalibrateSoakTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelCalibrateSoakTime, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SettingsLabelCalibrateSoakTime, "Calibrate Heatsoak");
    lv_obj_set_style_text_color(ui_SettingsLabelCalibrateSoakTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsLabelCalibrateSoakTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsLabelCalibrateSoakTime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SettingsLabelCalibrateSoakTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsLabelCalibrateSoakTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsLabelCalibrateSoakTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsLabelCalibrateSoakTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButtonClearLogs = lv_button_create(ui_SettingsPanelMain);
    lv_obj_set_width(ui_SettingsButtonClearLogs, 240);
    lv_obj_set_height(ui_SettingsButtonClearLogs, 40);
    lv_obj_set_x(ui_SettingsButtonClearLogs, -30);
    lv_obj_set_y(ui_SettingsButtonClearLogs, 110);
    lv_obj_set_align(ui_SettingsButtonClearLogs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButtonClearLogs, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettingsButtonClearLogs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsButtonClearLogs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsButtonClearLogs, lv_color_hex(0x980000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsButtonClearLogs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsButtonClearLogs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsButtonClearLogs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsButtonClearLogs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelClearLogs = lv_label_create(ui_SettingsButtonClearLogs);
    lv_obj_set_width(ui_SettingsLabelClearLogs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelClearLogs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelClearLogs, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SettingsLabelClearLogs, "Clear Logs");
    lv_obj_set_style_text_font(ui_SettingsLabelClearLogs, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SettingsLabelClearLogs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsLabelClearLogs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsLabelClearLogs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsLabelClearLogs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButtonExit = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_SettingsButtonExit, 50);
    lv_obj_set_height(ui_SettingsButtonExit, 50);
    lv_obj_set_x(ui_SettingsButtonExit, 130);
    lv_obj_set_y(ui_SettingsButtonExit, -90);
    lv_obj_set_align(ui_SettingsButtonExit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButtonExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettingsButtonExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsButtonExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsButtonExit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsButtonExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelExit = lv_label_create(ui_SettingsButtonExit);
    lv_obj_set_width(ui_SettingsLabelExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelExit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsLabelExit, "X");
    lv_obj_set_style_text_color(ui_SettingsLabelExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsLabelExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsLabelExit, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsContainerSD = lv_obj_create(ui_ScreenSettings);
    lv_obj_remove_style_all(ui_SettingsContainerSD);
    lv_obj_set_width(ui_SettingsContainerSD, 60);
    lv_obj_set_height(ui_SettingsContainerSD, 30);
    lv_obj_set_x(ui_SettingsContainerSD, 125);
    lv_obj_set_y(ui_SettingsContainerSD, -30);
    lv_obj_set_align(ui_SettingsContainerSD, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsContainerSD, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsContainerSD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsContainerSD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsContainerSD, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelSDTitle = lv_label_create(ui_SettingsContainerSD);
    lv_obj_set_width(ui_SettingsLabelSDTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelSDTitle, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_SettingsLabelSDTitle, "SD free:");
    lv_obj_set_style_text_color(ui_SettingsLabelSDTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsLabelSDTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelSDFree = lv_label_create(ui_SettingsContainerSD);
    lv_obj_set_width(ui_SettingsLabelSDFree, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelSDFree, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelSDFree, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_SettingsLabelSDFree, "000 MB");
    lv_obj_set_style_text_color(ui_SettingsLabelSDFree, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsLabelSDFree, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsContainerBrewCount = lv_obj_create(ui_ScreenSettings);
    lv_obj_remove_style_all(ui_SettingsContainerBrewCount);
    lv_obj_set_width(ui_SettingsContainerBrewCount, 60);
    lv_obj_set_height(ui_SettingsContainerBrewCount, 30);
    lv_obj_set_x(ui_SettingsContainerBrewCount, 125);
    lv_obj_set_y(ui_SettingsContainerBrewCount, 30);
    lv_obj_set_align(ui_SettingsContainerBrewCount, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsContainerBrewCount, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsContainerBrewCount, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsContainerBrewCount, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsContainerBrewCount, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsContainerBrewCount, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsContainerBrewCount, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsContainerBrewCount, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelBrewCountTitle = lv_label_create(ui_SettingsContainerBrewCount);
    lv_obj_set_width(ui_SettingsLabelBrewCountTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelBrewCountTitle, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_SettingsLabelBrewCountTitle, "Brews:");
    lv_obj_set_style_text_color(ui_SettingsLabelBrewCountTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsLabelBrewCountTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelBrewCountNum = lv_label_create(ui_SettingsContainerBrewCount);
    lv_obj_set_width(ui_SettingsLabelBrewCountNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelBrewCountNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelBrewCountNum, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_SettingsLabelBrewCountNum, "0");
    lv_obj_set_style_text_color(ui_SettingsLabelBrewCountNum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsLabelBrewCountNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsContainerFWVer = lv_obj_create(ui_ScreenSettings);
    lv_obj_remove_style_all(ui_SettingsContainerFWVer);
    lv_obj_set_width(ui_SettingsContainerFWVer, 60);
    lv_obj_set_height(ui_SettingsContainerFWVer, 30);
    lv_obj_set_x(ui_SettingsContainerFWVer, 125);
    lv_obj_set_y(ui_SettingsContainerFWVer, 90);
    lv_obj_set_align(ui_SettingsContainerFWVer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsContainerFWVer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsContainerFWVer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsContainerFWVer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelFWVerTitle = lv_label_create(ui_SettingsContainerFWVer);
    lv_obj_set_width(ui_SettingsLabelFWVerTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelFWVerTitle, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_SettingsLabelFWVerTitle, "FW ver:");
    lv_obj_set_style_text_color(ui_SettingsLabelFWVerTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsLabelFWVerTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelFWVerNum = lv_label_create(ui_SettingsContainerFWVer);
    lv_obj_set_width(ui_SettingsLabelFWVerNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelFWVerNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelFWVerNum, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_SettingsLabelFWVerNum, "1.0");
    lv_obj_set_style_text_color(ui_SettingsLabelFWVerNum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsLabelFWVerNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenSettings_screen_destroy(void)
{
    if(ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

    // NULL screen variables
    ui_ScreenSettings = NULL;
    ui_SettingsPanelMain = NULL;
    ui_SettingsDropdownGHTemp = NULL;
    ui_SettingsDropdownBoilerTemp = NULL;
    ui_SettingsDropdownMusicSelect = NULL;
    ui_SettingsButtonCalibrateSoakTime = NULL;
    ui_SettingsSpinboxHeatsoak = NULL;
    ui_SettingsLabelCalibrateSoakTime = NULL;
    ui_SettingsButtonClearLogs = NULL;
    ui_SettingsLabelClearLogs = NULL;
    ui_SettingsButtonExit = NULL;
    ui_SettingsLabelExit = NULL;
    ui_SettingsContainerSD = NULL;
    ui_SettingsLabelSDTitle = NULL;
    ui_SettingsLabelSDFree = NULL;
    ui_SettingsContainerBrewCount = NULL;
    ui_SettingsLabelBrewCountTitle = NULL;
    ui_SettingsLabelBrewCountNum = NULL;
    ui_SettingsContainerFWVer = NULL;
    ui_SettingsLabelFWVerTitle = NULL;
    ui_SettingsLabelFWVerNum = NULL;

}
