// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#include "ui.h"

lv_obj_t * ui_ScreenWarmup = NULL;
lv_obj_t * ui_WarmupBarWater = NULL;
lv_obj_t * ui_WarmupImgWave = NULL;
lv_obj_t * ui_WarmupPanelOverlay = NULL;
lv_obj_t * ui_WarmupPanelBottomBar = NULL;
lv_obj_t * ui_WarmupPanelIcons = NULL;
lv_obj_t * ui_WarmupLabelWiFi = NULL;
lv_obj_t * ui_WarmupLabelSD = NULL;
lv_obj_t * ui_WarmupBtnSettings = NULL;
lv_obj_t * ui_WarmupLabelSettings = NULL;
lv_obj_t * ui_WarmupPanelTopBar = NULL;
lv_obj_t * ui_WarmupLabelStatus = NULL;
lv_obj_t * ui_WarmupBtnGame = NULL;
lv_obj_t * ui_WarmupLabelGame = NULL;
lv_obj_t * ui_WarmupArcBoiler = NULL;
lv_obj_t * ui_WarmupPanelTemp = NULL;
lv_obj_t * ui_WarmupLabelBoiler = NULL;
lv_obj_t * ui_WarmupLabelBoilerTemp = NULL;
lv_obj_t * ui_WarmupPanelGrouphead = NULL;
lv_obj_t * ui_WarmupLabelGrouphead = NULL;
lv_obj_t * ui_WarmupLabelGroupheadTemp = NULL;
// event funtions

// build funtions

void ui_ScreenWarmup_screen_init(void)
{
    ui_ScreenWarmup = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenWarmup, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags

    ui_WarmupBarWater = lv_bar_create(ui_ScreenWarmup);
    lv_bar_set_range(ui_WarmupBarWater, 0, 321);
    lv_bar_set_value(ui_WarmupBarWater, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_WarmupBarWater, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_WarmupBarWater, 320);
    lv_obj_set_height(ui_WarmupBarWater, 321);
    lv_obj_set_align(ui_WarmupBarWater, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_WarmupBarWater,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_WarmupBarWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarmupBarWater, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarmupBarWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WarmupBarWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_WarmupBarWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_WarmupBarWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WarmupBarWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WarmupBarWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WarmupBarWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WarmupBarWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_WarmupBarWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_WarmupBarWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_WarmupBarWater, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarmupBarWater, lv_color_hex(0x0000FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarmupBarWater, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WarmupBarWater, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_WarmupBarWater, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_WarmupBarWater,
                                                                                                     lv_obj_get_style_pad_right(ui_WarmupBarWater, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_WarmupImgWave = lv_image_create(ui_ScreenWarmup);
    lv_image_set_src(ui_WarmupImgWave, &ui_img_487075786);
    lv_obj_set_width(ui_WarmupImgWave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarmupImgWave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarmupImgWave, 0);
    lv_obj_set_y(ui_WarmupImgWave, lv_pct(55));
    lv_obj_set_align(ui_WarmupImgWave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarmupImgWave, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_WarmupImgWave,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_inner_align(ui_WarmupImgWave, LV_IMAGE_ALIGN_TOP_MID);
    lv_obj_set_style_image_recolor(ui_WarmupImgWave, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_WarmupImgWave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarmupPanelOverlay = lv_obj_create(ui_ScreenWarmup);
    lv_obj_set_width(ui_WarmupPanelOverlay, 320);
    lv_obj_set_height(ui_WarmupPanelOverlay, 240);
    lv_obj_set_align(ui_WarmupPanelOverlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarmupPanelOverlay, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_WarmupPanelOverlay,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_WarmupPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarmupPanelOverlay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarmupPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_WarmupPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WarmupPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_WarmupPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_WarmupPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WarmupPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WarmupPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_WarmupPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_WarmupPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_WarmupPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_WarmupPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_WarmupPanelOverlay, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarmupPanelOverlay, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarmupPanelOverlay, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_WarmupPanelBottomBar = lv_obj_create(ui_WarmupPanelOverlay);
    lv_obj_set_width(ui_WarmupPanelBottomBar, 320);
    lv_obj_set_height(ui_WarmupPanelBottomBar, 22);
    lv_obj_set_x(ui_WarmupPanelBottomBar, 0);
    lv_obj_set_y(ui_WarmupPanelBottomBar, 13);
    lv_obj_set_align(ui_WarmupPanelBottomBar, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_WarmupPanelBottomBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WarmupPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarmupPanelBottomBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarmupPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WarmupPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_WarmupPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_WarmupPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WarmupPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WarmupPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_WarmupPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_WarmupPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarmupPanelIcons = lv_obj_create(ui_WarmupPanelBottomBar);
    lv_obj_set_width(ui_WarmupPanelIcons, 60);
    lv_obj_set_height(ui_WarmupPanelIcons, 20);
    lv_obj_set_x(ui_WarmupPanelIcons, 12);
    lv_obj_set_y(ui_WarmupPanelIcons, 0);
    lv_obj_set_align(ui_WarmupPanelIcons, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_WarmupPanelIcons,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_WarmupPanelIcons, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarmupPanelIcons, lv_color_hex(0x272727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarmupPanelIcons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WarmupPanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_WarmupPanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_WarmupPanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarmupLabelWiFi = lv_label_create(ui_WarmupPanelIcons);
    lv_obj_set_width(ui_WarmupLabelWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarmupLabelWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarmupLabelWiFi, 2);
    lv_obj_set_y(ui_WarmupLabelWiFi, 0);
    lv_obj_set_align(ui_WarmupLabelWiFi, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_WarmupLabelWiFi, "");

    ui_WarmupLabelSD = lv_label_create(ui_WarmupPanelIcons);
    lv_obj_set_width(ui_WarmupLabelSD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarmupLabelSD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarmupLabelSD, -2);
    lv_obj_set_y(ui_WarmupLabelSD, 0);
    lv_obj_set_align(ui_WarmupLabelSD, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WarmupLabelSD, "SD");

    ui_WarmupBtnSettings = lv_button_create(ui_WarmupPanelBottomBar);
    lv_obj_set_width(ui_WarmupBtnSettings, 20);
    lv_obj_set_height(ui_WarmupBtnSettings, 20);
    lv_obj_set_x(ui_WarmupBtnSettings, -11);
    lv_obj_set_y(ui_WarmupBtnSettings, 0);
    lv_obj_set_align(ui_WarmupBtnSettings, LV_ALIGN_LEFT_MID);
    lv_obj_set_ext_click_area(ui_WarmupBtnSettings, 2);
    lv_obj_add_flag(ui_WarmupBtnSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_WarmupBtnSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WarmupBtnSettings, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarmupBtnSettings, lv_color_hex(0x7F7F7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarmupBtnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarmupLabelSettings = lv_label_create(ui_WarmupBtnSettings);
    lv_obj_set_width(ui_WarmupLabelSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarmupLabelSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WarmupLabelSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WarmupLabelSettings, "");

    ui_WarmupPanelTopBar = lv_obj_create(ui_WarmupPanelOverlay);
    lv_obj_set_width(ui_WarmupPanelTopBar, lv_pct(100));
    lv_obj_set_height(ui_WarmupPanelTopBar, lv_pct(15));
    lv_obj_set_x(ui_WarmupPanelTopBar, 0);
    lv_obj_set_y(ui_WarmupPanelTopBar, -10);
    lv_obj_set_align(ui_WarmupPanelTopBar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_WarmupPanelTopBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WarmupPanelTopBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarmupPanelTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WarmupPanelTopBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WarmupPanelTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarmupLabelStatus = lv_label_create(ui_WarmupPanelTopBar);
    lv_obj_set_width(ui_WarmupLabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarmupLabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarmupLabelStatus, -10);
    lv_obj_set_y(ui_WarmupLabelStatus, 0);
    lv_obj_set_align(ui_WarmupLabelStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WarmupLabelStatus, "WARMUP");
    lv_obj_set_style_text_color(ui_WarmupLabelStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WarmupLabelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_WarmupLabelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_WarmupLabelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WarmupLabelStatus, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_WarmupLabelStatus, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarmupLabelStatus, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarmupBtnGame = lv_button_create(ui_WarmupPanelTopBar);
    lv_obj_set_width(ui_WarmupBtnGame, 80);
    lv_obj_set_height(ui_WarmupBtnGame, 50);
    lv_obj_set_x(ui_WarmupBtnGame, 10);
    lv_obj_set_y(ui_WarmupBtnGame, 0);
    lv_obj_set_align(ui_WarmupBtnGame, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_WarmupBtnGame, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_WarmupBtnGame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WarmupLabelGame = lv_label_create(ui_WarmupBtnGame);
    lv_obj_set_width(ui_WarmupLabelGame, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarmupLabelGame, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WarmupLabelGame, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WarmupLabelGame, "GAME");

    ui_WarmupArcBoiler = lv_arc_create(ui_WarmupPanelOverlay);
    lv_obj_set_width(ui_WarmupArcBoiler, 190);
    lv_obj_set_height(ui_WarmupArcBoiler, 190);
    lv_obj_set_x(ui_WarmupArcBoiler, 0);
    lv_obj_set_y(ui_WarmupArcBoiler, 25);
    lv_obj_set_align(ui_WarmupArcBoiler, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WarmupArcBoiler, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_WarmupArcBoiler, 20, 118);
    lv_arc_set_value(ui_WarmupArcBoiler, 50);
    lv_obj_set_style_border_width(ui_WarmupArcBoiler, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_WarmupArcBoiler, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_WarmupArcBoiler, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_WarmupArcBoiler, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_WarmupPanelTemp = lv_obj_create(ui_WarmupPanelOverlay);
    lv_obj_set_width(ui_WarmupPanelTemp, 200);
    lv_obj_set_height(ui_WarmupPanelTemp, 75);
    lv_obj_set_x(ui_WarmupPanelTemp, 0);
    lv_obj_set_y(ui_WarmupPanelTemp, 20);
    lv_obj_set_align(ui_WarmupPanelTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarmupPanelTemp, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_WarmupPanelTemp,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_WarmupPanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarmupPanelTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarmupPanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WarmupPanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_WarmupPanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_WarmupPanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarmupLabelBoiler = lv_label_create(ui_WarmupPanelTemp);
    lv_obj_set_width(ui_WarmupLabelBoiler, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarmupLabelBoiler, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarmupLabelBoiler, 0);
    lv_obj_set_y(ui_WarmupLabelBoiler, -15);
    lv_obj_set_align(ui_WarmupLabelBoiler, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WarmupLabelBoiler, "Boiler Temperature");
    lv_obj_add_flag(ui_WarmupLabelBoiler, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_set_style_text_font(ui_WarmupLabelBoiler, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarmupLabelBoilerTemp = lv_label_create(ui_WarmupPanelTemp);
    lv_obj_set_width(ui_WarmupLabelBoilerTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarmupLabelBoilerTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarmupLabelBoilerTemp, 0);
    lv_obj_set_y(ui_WarmupLabelBoilerTemp, 15);
    lv_obj_set_align(ui_WarmupLabelBoilerTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WarmupLabelBoilerTemp, "25.0C");
    lv_obj_set_style_text_font(ui_WarmupLabelBoilerTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarmupPanelGrouphead = lv_obj_create(ui_WarmupPanelOverlay);
    lv_obj_set_width(ui_WarmupPanelGrouphead, 200);
    lv_obj_set_height(ui_WarmupPanelGrouphead, 75);
    lv_obj_set_x(ui_WarmupPanelGrouphead, 0);
    lv_obj_set_y(ui_WarmupPanelGrouphead, 50);
    lv_obj_set_align(ui_WarmupPanelGrouphead, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarmupPanelGrouphead, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_WarmupPanelGrouphead,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_WarmupPanelGrouphead, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarmupPanelGrouphead, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarmupPanelGrouphead, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WarmupPanelGrouphead, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarmupLabelGrouphead = lv_label_create(ui_WarmupPanelGrouphead);
    lv_obj_set_width(ui_WarmupLabelGrouphead, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarmupLabelGrouphead, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarmupLabelGrouphead, 0);
    lv_obj_set_y(ui_WarmupLabelGrouphead, -15);
    lv_obj_set_align(ui_WarmupLabelGrouphead, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WarmupLabelGrouphead, "Grouphead Temperature\n(estimated)");
    lv_obj_add_flag(ui_WarmupLabelGrouphead, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_set_style_text_align(ui_WarmupLabelGrouphead, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarmupLabelGrouphead, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarmupLabelGroupheadTemp = lv_label_create(ui_WarmupPanelGrouphead);
    lv_obj_set_width(ui_WarmupLabelGroupheadTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarmupLabelGroupheadTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WarmupLabelGroupheadTemp, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WarmupLabelGroupheadTemp, "25.0C");
    lv_obj_set_style_text_font(ui_WarmupLabelGroupheadTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenWarmup_screen_destroy(void)
{
    if(ui_ScreenWarmup) lv_obj_del(ui_ScreenWarmup);

    // NULL screen variables
    ui_ScreenWarmup = NULL;
    ui_WarmupBarWater = NULL;
    ui_WarmupImgWave = NULL;
    ui_WarmupPanelOverlay = NULL;
    ui_WarmupPanelBottomBar = NULL;
    ui_WarmupPanelIcons = NULL;
    ui_WarmupLabelWiFi = NULL;
    ui_WarmupLabelSD = NULL;
    ui_WarmupBtnSettings = NULL;
    ui_WarmupLabelSettings = NULL;
    ui_WarmupPanelTopBar = NULL;
    ui_WarmupLabelStatus = NULL;
    ui_WarmupBtnGame = NULL;
    ui_WarmupLabelGame = NULL;
    ui_WarmupArcBoiler = NULL;
    ui_WarmupPanelTemp = NULL;
    ui_WarmupLabelBoiler = NULL;
    ui_WarmupLabelBoilerTemp = NULL;
    ui_WarmupPanelGrouphead = NULL;
    ui_WarmupLabelGrouphead = NULL;
    ui_WarmupLabelGroupheadTemp = NULL;

}
