// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#ifndef UI_SCREENDONE_H
#define UI_SCREENDONE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenDone
extern void ui_ScreenDone_screen_init(void);
extern void ui_ScreenDone_screen_destroy(void);
extern lv_obj_t * ui_ScreenDone;
extern lv_obj_t * ui_DonePanelOverlay;
extern lv_obj_t * ui_DonePanelBottomBar;
extern lv_obj_t * ui_DonePanelIcons;
extern lv_obj_t * ui_DoneLabelWiFi;
extern lv_obj_t * ui_DoneLabelSD;
extern lv_obj_t * ui_DoneBtnSettings;
extern lv_obj_t * ui_DoneLabelSettings;
extern lv_obj_t * ui_DonePanelTopBar;
extern lv_obj_t * ui_DoneLabelStatus;
extern lv_obj_t * ui_DoneLabelUploading;
extern lv_obj_t * ui_DoneChart;
extern lv_obj_t * ui_DoneChart_Xaxis;
extern lv_obj_t * ui_DoneChart_Yaxis1;
extern lv_obj_t * ui_DoneChart_Yaxis2;
extern lv_obj_t * ui_DonePanelTime;
extern lv_obj_t * ui_DoneLabelTimeTenths;
extern lv_obj_t * ui_DoneLabelTimeSeconds;
extern lv_obj_t * ui_DoneLabelTimeDot;
extern lv_obj_t * ui_DonePanelRate;
extern lv_obj_t * ui_DoneImageGuy;
extern lv_obj_t * ui_DoneLabelRate;
extern lv_obj_t * ui_DoneSliderRate;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

