// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#include "ui.h"

lv_obj_t * uic_ScreenReady;
lv_obj_t * ui_ScreenReady = NULL;
lv_obj_t * ui_ReadyImageBg = NULL;
lv_obj_t * ui_ReadyPanelOverlay = NULL;
lv_obj_t * ui_ReadyPanelBottomBar = NULL;
lv_obj_t * ui_ReadyPanelIcons = NULL;
lv_obj_t * ui_ReadyLabelWiFi = NULL;
lv_obj_t * ui_ReadyLabelSD = NULL;
lv_obj_t * ui_ReadyBtnSettings = NULL;
lv_obj_t * ui_ReadyLabelSettings = NULL;
lv_obj_t * ui_ReadyPanelTopBar = NULL;
lv_obj_t * ui_ReadyLabelStatus = NULL;
lv_obj_t * ui_ReadyLabelFlush = NULL;
lv_obj_t * ui_ReadyPanelTime = NULL;
lv_obj_t * ui_ReadyLabelTimeSeconds = NULL;
lv_obj_t * ui_ReadyLabelTimeMinutes = NULL;
lv_obj_t * ui_ReadyLabelTimeColon = NULL;
lv_obj_t * ui_ReadyButtonTemp = NULL;
lv_obj_t * ui_ReadyLabelTemp = NULL;
// event funtions

// build funtions

void ui_ScreenReady_screen_init(void)
{
    ui_ScreenReady = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenReady, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags

    ui_ReadyImageBg = lv_image_create(ui_ScreenReady);
    lv_image_set_src(ui_ReadyImageBg, &ui_img_fieldwarcartoon480240blur_reduced_png);
    lv_obj_set_width(ui_ReadyImageBg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReadyImageBg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReadyImageBg, -50);
    lv_obj_set_y(ui_ReadyImageBg, 0);
    lv_obj_set_align(ui_ReadyImageBg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReadyImageBg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ReadyImageBg, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_opa(ui_ReadyImageBg, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyPanelOverlay = lv_obj_create(ui_ScreenReady);
    lv_obj_set_width(ui_ReadyPanelOverlay, 320);
    lv_obj_set_height(ui_ReadyPanelOverlay, 240);
    lv_obj_set_align(ui_ReadyPanelOverlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReadyPanelOverlay, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_ReadyPanelOverlay,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ReadyPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadyPanelOverlay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadyPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_ReadyPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReadyPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ReadyPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ReadyPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ReadyPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ReadyPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_ReadyPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_ReadyPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ReadyPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ReadyPanelOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ReadyPanelOverlay, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ReadyPanelBottomBar = lv_obj_create(ui_ReadyPanelOverlay);
    lv_obj_set_width(ui_ReadyPanelBottomBar, 320);
    lv_obj_set_height(ui_ReadyPanelBottomBar, 22);
    lv_obj_set_x(ui_ReadyPanelBottomBar, 0);
    lv_obj_set_y(ui_ReadyPanelBottomBar, 13);
    lv_obj_set_align(ui_ReadyPanelBottomBar, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_ReadyPanelBottomBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReadyPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadyPanelBottomBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadyPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReadyPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ReadyPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ReadyPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ReadyPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ReadyPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_ReadyPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_ReadyPanelBottomBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyPanelIcons = lv_obj_create(ui_ReadyPanelBottomBar);
    lv_obj_set_width(ui_ReadyPanelIcons, 60);
    lv_obj_set_height(ui_ReadyPanelIcons, 20);
    lv_obj_set_x(ui_ReadyPanelIcons, 12);
    lv_obj_set_y(ui_ReadyPanelIcons, 0);
    lv_obj_set_align(ui_ReadyPanelIcons, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_ReadyPanelIcons,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ReadyPanelIcons, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadyPanelIcons, lv_color_hex(0x272727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadyPanelIcons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReadyPanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ReadyPanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ReadyPanelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyLabelWiFi = lv_label_create(ui_ReadyPanelIcons);
    lv_obj_set_width(ui_ReadyLabelWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReadyLabelWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReadyLabelWiFi, 2);
    lv_obj_set_y(ui_ReadyLabelWiFi, 0);
    lv_obj_set_align(ui_ReadyLabelWiFi, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ReadyLabelWiFi, "");

    ui_ReadyLabelSD = lv_label_create(ui_ReadyPanelIcons);
    lv_obj_set_width(ui_ReadyLabelSD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReadyLabelSD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReadyLabelSD, -2);
    lv_obj_set_y(ui_ReadyLabelSD, 0);
    lv_obj_set_align(ui_ReadyLabelSD, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ReadyLabelSD, "SD");

    ui_ReadyBtnSettings = lv_button_create(ui_ReadyPanelBottomBar);
    lv_obj_set_width(ui_ReadyBtnSettings, 20);
    lv_obj_set_height(ui_ReadyBtnSettings, 20);
    lv_obj_set_x(ui_ReadyBtnSettings, -11);
    lv_obj_set_y(ui_ReadyBtnSettings, 0);
    lv_obj_set_align(ui_ReadyBtnSettings, LV_ALIGN_LEFT_MID);
    lv_obj_set_ext_click_area(ui_ReadyBtnSettings, 2);
    lv_obj_add_flag(ui_ReadyBtnSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ReadyBtnSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReadyBtnSettings, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadyBtnSettings, lv_color_hex(0x7F7F7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadyBtnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyLabelSettings = lv_label_create(ui_ReadyBtnSettings);
    lv_obj_set_width(ui_ReadyLabelSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReadyLabelSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ReadyLabelSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReadyLabelSettings, "");

    ui_ReadyPanelTopBar = lv_obj_create(ui_ReadyPanelOverlay);
    lv_obj_set_width(ui_ReadyPanelTopBar, lv_pct(100));
    lv_obj_set_height(ui_ReadyPanelTopBar, lv_pct(15));
    lv_obj_set_x(ui_ReadyPanelTopBar, 0);
    lv_obj_set_y(ui_ReadyPanelTopBar, -10);
    lv_obj_set_align(ui_ReadyPanelTopBar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ReadyPanelTopBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReadyPanelTopBar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadyPanelTopBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadyPanelTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReadyPanelTopBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReadyPanelTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyLabelStatus = lv_label_create(ui_ReadyPanelTopBar);
    lv_obj_set_width(ui_ReadyLabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReadyLabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReadyLabelStatus, -10);
    lv_obj_set_y(ui_ReadyLabelStatus, 0);
    lv_obj_set_align(ui_ReadyLabelStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ReadyLabelStatus, "READY");
    lv_obj_set_style_text_color(ui_ReadyLabelStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReadyLabelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_ReadyLabelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ReadyLabelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ReadyLabelStatus, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ReadyLabelStatus, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadyLabelStatus, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyLabelFlush = lv_label_create(ui_ReadyPanelTopBar);
    lv_obj_set_width(ui_ReadyLabelFlush, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReadyLabelFlush, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ReadyLabelFlush, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ReadyLabelFlush, "HOT FLUSH\nRECOMMENDED");
    lv_obj_remove_flag(ui_ReadyLabelFlush,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_ReadyLabelFlush, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReadyLabelFlush, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ReadyLabelFlush, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadyLabelFlush, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ReadyLabelFlush, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadyLabelFlush, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadyLabelFlush, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyPanelTime = lv_obj_create(ui_ReadyPanelOverlay);
    lv_obj_set_width(ui_ReadyPanelTime, 200);
    lv_obj_set_height(ui_ReadyPanelTime, 60);
    lv_obj_set_x(ui_ReadyPanelTime, 0);
    lv_obj_set_y(ui_ReadyPanelTime, -30);
    lv_obj_set_align(ui_ReadyPanelTime, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReadyPanelTime,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ReadyPanelTime, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadyPanelTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadyPanelTime, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReadyPanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyLabelTimeSeconds = lv_label_create(ui_ReadyPanelTime);
    lv_obj_set_width(ui_ReadyLabelTimeSeconds, 75);
    lv_obj_set_height(ui_ReadyLabelTimeSeconds, 60);
    lv_obj_set_x(ui_ReadyLabelTimeSeconds, 40);
    lv_obj_set_y(ui_ReadyLabelTimeSeconds, 0);
    lv_obj_set_align(ui_ReadyLabelTimeSeconds, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReadyLabelTimeSeconds, "88");
    lv_obj_remove_flag(ui_ReadyLabelTimeSeconds,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_ReadyLabelTimeSeconds, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadyLabelTimeSeconds, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyLabelTimeMinutes = lv_label_create(ui_ReadyPanelTime);
    lv_obj_set_width(ui_ReadyLabelTimeMinutes, 75);
    lv_obj_set_height(ui_ReadyLabelTimeMinutes, 60);
    lv_obj_set_x(ui_ReadyLabelTimeMinutes, -40);
    lv_obj_set_y(ui_ReadyLabelTimeMinutes, 0);
    lv_obj_set_align(ui_ReadyLabelTimeMinutes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReadyLabelTimeMinutes, "88");
    lv_obj_remove_flag(ui_ReadyLabelTimeMinutes,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_ReadyLabelTimeMinutes, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadyLabelTimeMinutes, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyLabelTimeColon = lv_label_create(ui_ReadyPanelTime);
    lv_obj_set_width(ui_ReadyLabelTimeColon, 20);
    lv_obj_set_height(ui_ReadyLabelTimeColon, 60);
    lv_obj_set_align(ui_ReadyLabelTimeColon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReadyLabelTimeColon, ":");
    lv_obj_remove_flag(ui_ReadyLabelTimeColon,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_ReadyLabelTimeColon, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadyLabelTimeColon, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyButtonTemp = lv_button_create(ui_ReadyPanelOverlay);
    lv_obj_set_width(ui_ReadyButtonTemp, 225);
    lv_obj_set_height(ui_ReadyButtonTemp, 70);
    lv_obj_set_x(ui_ReadyButtonTemp, 0);
    lv_obj_set_y(ui_ReadyButtonTemp, 50);
    lv_obj_set_align(ui_ReadyButtonTemp, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReadyButtonTemp,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ReadyButtonTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadyButtonTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadyButtonTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReadyButtonTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ReadyButtonTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ReadyButtonTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyLabelTemp = lv_label_create(ui_ReadyButtonTemp);
    lv_obj_set_width(ui_ReadyLabelTemp, lv_pct(100));
    lv_obj_set_height(ui_ReadyLabelTemp, lv_pct(100));
    lv_obj_set_align(ui_ReadyLabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReadyLabelTemp, "25.0C");
    lv_obj_remove_flag(ui_ReadyLabelTemp,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_ReadyLabelTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadyLabelTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ReadyLabelTemp, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadyLabelTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadyLabelTemp, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_ScreenReady = ui_ScreenReady;

}

void ui_ScreenReady_screen_destroy(void)
{
    if(ui_ScreenReady) lv_obj_del(ui_ScreenReady);

    // NULL screen variables
    uic_ScreenReady = NULL;
    ui_ScreenReady = NULL;
    ui_ReadyImageBg = NULL;
    ui_ReadyPanelOverlay = NULL;
    ui_ReadyPanelBottomBar = NULL;
    ui_ReadyPanelIcons = NULL;
    ui_ReadyLabelWiFi = NULL;
    ui_ReadyLabelSD = NULL;
    ui_ReadyBtnSettings = NULL;
    ui_ReadyLabelSettings = NULL;
    ui_ReadyPanelTopBar = NULL;
    ui_ReadyLabelStatus = NULL;
    ui_ReadyLabelFlush = NULL;
    ui_ReadyPanelTime = NULL;
    ui_ReadyLabelTimeSeconds = NULL;
    ui_ReadyLabelTimeMinutes = NULL;
    ui_ReadyLabelTimeColon = NULL;
    ui_ReadyButtonTemp = NULL;
    ui_ReadyLabelTemp = NULL;

}
