// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_EspressoMonitor

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_SettingsPanelMain;
extern lv_obj_t * ui_SettingsDropdownGHTemp;
extern lv_obj_t * ui_SettingsDropdownBoilerTemp;
extern lv_obj_t * ui_SettingsDropdownMusicSelect;
extern lv_obj_t * ui_SettingsButtonCalibrateSoakTime;
extern lv_obj_t * ui_SettingsSpinboxHeatsoak;
extern lv_obj_t * ui_SettingsLabelCalibrateSoakTime;
extern lv_obj_t * ui_SettingsButtonClearLogs;
extern lv_obj_t * ui_SettingsLabelClearLogs;
extern lv_obj_t * ui_SettingsButtonExit;
extern lv_obj_t * ui_SettingsLabelExit;
extern lv_obj_t * ui_SettingsContainerSD;
extern lv_obj_t * ui_SettingsLabelSDTitle;
extern lv_obj_t * ui_SettingsLabelSDFree;
extern lv_obj_t * ui_SettingsContainerBrewCount;
extern lv_obj_t * ui_SettingsLabelBrewCountTitle;
extern lv_obj_t * ui_SettingsLabelBrewCountNum;
extern lv_obj_t * ui_SettingsContainerFWVer;
extern lv_obj_t * ui_SettingsLabelFWVerTitle;
extern lv_obj_t * ui_SettingsLabelFWVerNum;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

